-- ViiA Pick — Phase 1 schema
-- Implements References/viia-specs-phase1.md §2 (modèle de données) and the
-- concurrency-safe id generation required by §3.0.
--
-- Design notes / deliberate deviations from the literal spec wording:
--   * TrackSegment.points (spec: array of {lat,lng,timestamp}) is normalized
--     into a separate track_point table instead of a JSONB array column, so
--     that GPS points can be appended one at a time (every 3-5s) without
--     rewriting a growing array on each write.
--   * MissionAssignment gains a `completed_at` column, not listed in the
--     spec's table but implied by "Terminer sa part de mission" (§3.1.5):
--     needed to know when *this* operator is done, so the mission can flip
--     to `completed` once every assignment is.
--   * A `client` table is added — the spec references `client_id` on
--     Mission but never defines the Client entity's own columns.

create extension if not exists pgcrypto;

-- ============================================================================
-- CORE TABLES
-- ============================================================================

create table city (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  code text not null unique,
  created_at timestamptz not null default now()
);

create table client (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table operator (
  id uuid primary key default gen_random_uuid(),
  matricule text unique, -- generated by trigger, see set_operator_matricule()
  name text not null,
  contact text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now()
);

create table mission (
  id uuid primary key default gen_random_uuid(),
  reference text unique, -- generated by trigger, see set_mission_reference()
  client_id uuid references client(id),
  city_id uuid not null references city(id),
  date date not null,
  status text not null default 'planned' check (status in ('planned', 'in_progress', 'completed')),
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now()
);

create table mission_assignment (
  id uuid primary key default gen_random_uuid(),
  mission_id uuid not null references mission(id) on delete cascade,
  operator_id uuid not null references operator(id),
  completed_at timestamptz,
  unique (mission_id, operator_id)
);

create table track_segment (
  id uuid primary key default gen_random_uuid(),
  mission_id uuid not null references mission(id) on delete cascade,
  operator_id uuid not null references operator(id),
  source text not null default 'vehicle' check (source in ('vehicle', 'manual')),
  created_at timestamptz not null default now()
);

create table track_point (
  id bigserial primary key,
  segment_id uuid not null references track_segment(id) on delete cascade,
  lat double precision not null,
  lng double precision not null,
  recorded_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index track_point_segment_id_idx on track_point(segment_id, recorded_at);

create table weighing (
  id uuid primary key default gen_random_uuid(),
  mission_id uuid not null references mission(id) on delete cascade,
  operator_id uuid not null references operator(id),
  kilos_total numeric(10, 2) not null check (kilos_total >= 0),
  kilos_recycled numeric(10, 2) not null check (kilos_recycled >= 0 and kilos_recycled <= kilos_total),
  recorded_at timestamptz not null default now(),
  unique (mission_id, operator_id)
);

-- app_user links a Supabase auth identity to a role + scope. Managed only
-- by managers (see RLS below) — provisioning a login is a manager action.
create table app_user (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('operator', 'manager', 'client', 'city')),
  operator_id uuid references operator(id),
  client_id uuid references client(id),
  city_id uuid references city(id),
  created_at timestamptz not null default now(),
  constraint app_user_scope_matches_role check (
    (role = 'operator' and operator_id is not null and client_id is null and city_id is null) or
    (role = 'manager' and operator_id is null and client_id is null and city_id is null) or
    (role = 'client' and client_id is not null and operator_id is null and city_id is null) or
    (role = 'city' and city_id is not null and operator_id is null and client_id is null)
  )
);

-- ============================================================================
-- ATOMIC / CONCURRENCY-SAFE ID GENERATION (§3.0)
--   "deux créations simultanées ne doivent jamais produire le même numéro"
-- ============================================================================

-- Operator matricule: single global counter, a real Postgres sequence is the
-- simplest correct primitive (nextval() is atomic under concurrent callers).
create sequence operator_matricule_seq start 1;

create or replace function public.set_operator_matricule() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.matricule is null then
    new.matricule := 'OP-' || lpad(nextval('operator_matricule_seq')::text, 5, '0');
  end if;
  return new;
end;
$$;

create trigger trg_operator_matricule
before insert on operator
for each row execute function public.set_operator_matricule();

-- Mission reference: counter is per-city, and cities are created at runtime,
-- so a static sequence per city isn't an option. Instead: one counter row per
-- city, incremented via `UPDATE ... RETURNING`, which takes a row lock — a
-- second concurrent transaction blocks on that row until the first commits,
-- so two simultaneous inserts for the same city can never read the same
-- value. This is the safe alternative to a "select max()+1" race.
create table city_mission_counter (
  city_id uuid primary key references city(id) on delete cascade,
  next_seq bigint not null default 1
);

create or replace function public.ensure_city_counter() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into city_mission_counter (city_id) values (new.id);
  return new;
end;
$$;

create trigger trg_city_counter
after insert on city
for each row execute function public.ensure_city_counter();

create or replace function public.next_mission_reference(p_city_id uuid) returns text
language plpgsql security definer set search_path = public as $$
declare
  v_code text;
  v_seq bigint;
begin
  select code into v_code from city where id = p_city_id;
  if v_code is null then
    raise exception 'unknown city_id %', p_city_id;
  end if;

  update city_mission_counter
  set next_seq = next_seq + 1
  where city_id = p_city_id
  returning next_seq - 1 into v_seq;

  if v_seq is null then
    -- Defensive fallback: counter row missing (shouldn't happen given the
    -- trigger above, but avoids a hard failure if a city predates it).
    insert into city_mission_counter (city_id, next_seq) values (p_city_id, 2);
    v_seq := 1;
  end if;

  return v_code || '-' || lpad(v_seq::text, 5, '0');
end;
$$;

create or replace function public.set_mission_reference() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.reference is null then
    new.reference := public.next_mission_reference(new.city_id);
  end if;
  return new;
end;
$$;

create trigger trg_mission_reference
before insert on mission
for each row execute function public.set_mission_reference();

-- ============================================================================
-- MISSION WORKFLOW (§3.1.3 / §3.1.5)
--   in_progress + started_at on first segment; completed + ended_at once
--   every assigned operator has closed their part.
-- ============================================================================

create or replace function public.mark_mission_started() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  update mission
  set status = 'in_progress', started_at = coalesce(started_at, now())
  where id = new.mission_id and status = 'planned';
  return new;
end;
$$;

create trigger trg_mission_started
after insert on track_segment
for each row execute function public.mark_mission_started();

create or replace function public.mark_mission_completed() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_remaining int;
begin
  if new.completed_at is not null and old.completed_at is null then
    select count(*) into v_remaining
    from mission_assignment
    where mission_id = new.mission_id and completed_at is null;

    if v_remaining = 0 then
      update mission set status = 'completed', ended_at = now() where id = new.mission_id;
    end if;
  end if;
  return new;
end;
$$;

create trigger trg_mission_completed
after update of completed_at on mission_assignment
for each row execute function public.mark_mission_completed();

-- ============================================================================
-- ROLE / SCOPE HELPERS
--   security definer + fixed search_path so these read app_user without
--   recursing back into app_user's own RLS policies below.
-- ============================================================================

create or replace function public.app_role() returns text
language sql stable security definer set search_path = public as $$
  select role from app_user where id = auth.uid();
$$;

create or replace function public.app_operator_id() returns uuid
language sql stable security definer set search_path = public as $$
  select operator_id from app_user where id = auth.uid();
$$;

create or replace function public.app_client_id() returns uuid
language sql stable security definer set search_path = public as $$
  select client_id from app_user where id = auth.uid();
$$;

create or replace function public.app_city_id() returns uuid
language sql stable security definer set search_path = public as $$
  select city_id from app_user where id = auth.uid();
$$;

-- Shared visibility check for track_segment/track_point (mission-scoped, see
-- policies below for why client/city may see segment geometry but not
-- weighing rows).
create or replace function public.can_view_segment(p_segment_id uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1
    from track_segment ts
    join mission m on m.id = ts.mission_id
    where ts.id = p_segment_id
      and (
        app_role() = 'manager'
        or ts.operator_id = app_operator_id()
        or (app_role() = 'client' and m.client_id = app_client_id())
        or (app_role() = 'city' and m.city_id = app_city_id())
      )
  );
$$;

-- ============================================================================
-- AGGREGATED TOTALS FOR CLIENT/CITY (§2 "Le client/la ville ne voit que les
-- totaux mission" — never a raw weighing row, never a per-operator split).
-- security definer so it can read weighing despite the manager/operator-only
-- policy below; the function does its own scope check instead.
-- ============================================================================

create or replace function public.get_mission_totals(p_date_from date default null, p_date_to date default null)
returns table (
  mission_id uuid,
  reference text,
  city_id uuid,
  client_id uuid,
  date date,
  status text,
  kilos_total numeric,
  kilos_recycled numeric
)
language plpgsql security definer set search_path = public as $$
declare
  v_role text := app_role();
begin
  if v_role is null then
    raise exception 'no app_user profile for current user';
  end if;

  return query
  select
    m.id,
    m.reference,
    m.city_id,
    m.client_id,
    m.date,
    m.status,
    coalesce(sum(w.kilos_total), 0),
    coalesce(sum(w.kilos_recycled), 0)
  from mission m
  left join weighing w on w.mission_id = m.id
  where (p_date_from is null or m.date >= p_date_from)
    and (p_date_to is null or m.date <= p_date_to)
    and (
      v_role = 'manager'
      or (v_role = 'client' and m.client_id = app_client_id())
      or (v_role = 'city' and m.city_id = app_city_id())
    )
  group by m.id
  order by m.date desc;
end;
$$;

-- ============================================================================
-- ROW LEVEL SECURITY — cloisonnement obligatoire (§2)
-- ============================================================================

alter table city enable row level security;
alter table client enable row level security;
alter table operator enable row level security;
alter table mission enable row level security;
alter table mission_assignment enable row level security;
alter table track_segment enable row level security;
alter table track_point enable row level security;
alter table weighing enable row level security;
alter table app_user enable row level security;
alter table city_mission_counter enable row level security; -- no policies: internal only, touched solely via the definer functions above

-- app_user: see your own profile, manager sees/manages all
create policy app_user_select on app_user for select using (id = auth.uid() or app_role() = 'manager');
create policy app_user_write_manager on app_user for all using (app_role() = 'manager') with check (app_role() = 'manager');

-- city: reference data, readable by any signed-in role; writes are manager-only (§3.0)
create policy city_select on city for select using (auth.role() = 'authenticated');
create policy city_write_manager on city for all using (app_role() = 'manager') with check (app_role() = 'manager');

-- client: same pattern as city
create policy client_select on client for select using (auth.role() = 'authenticated');
create policy client_write_manager on client for all using (app_role() = 'manager') with check (app_role() = 'manager');

-- operator: manager sees/manages all; an operator may see their own record only
-- (client/city never see operator identities — "détail par opérateur réservé au manager")
create policy operator_select on operator for select using (app_role() = 'manager' or id = app_operator_id());
create policy operator_write_manager on operator for all using (app_role() = 'manager') with check (app_role() = 'manager');

-- mission: manager all; client/city scoped to their own; operator scoped to their assignments
create policy mission_select on mission for select using (
  app_role() = 'manager'
  or (app_role() = 'client' and client_id = app_client_id())
  or (app_role() = 'city' and city_id = app_city_id())
  or (app_role() = 'operator' and exists (
    select 1 from mission_assignment ma where ma.mission_id = mission.id and ma.operator_id = app_operator_id()
  ))
);
create policy mission_insert_manager on mission for insert with check (app_role() = 'manager');
create policy mission_update_manager on mission for update using (app_role() = 'manager') with check (app_role() = 'manager');
-- (status/started_at/ended_at auto-transitions run through the security definer
-- trigger functions above, which bypass this manager-only policy by design)

-- mission_assignment: manager manages; an operator sees + closes their own row
create policy assignment_select on mission_assignment for select using (
  app_role() = 'manager' or operator_id = app_operator_id()
);
create policy assignment_insert_manager on mission_assignment for insert with check (app_role() = 'manager');
create policy assignment_delete_manager on mission_assignment for delete using (app_role() = 'manager');
create policy assignment_update_self_or_manager on mission_assignment for update
  using (app_role() = 'manager' or operator_id = app_operator_id())
  with check (app_role() = 'manager' or operator_id = app_operator_id());

-- track_segment / track_point: manager all; operator their own; client/city
-- may read segment geometry for missions in their scope (needed for the map
-- in §3.3) but the frontend must always render it merged at mission level,
-- never split or labelled by operator — the "no individualized view" rule
-- from §2 is a rendering rule here, not a column-visibility one.
create policy track_segment_select on track_segment for select using (public.can_view_segment(id));
create policy track_segment_insert_self on track_segment for insert with check (operator_id = app_operator_id());

create policy track_point_select on track_point for select using (public.can_view_segment(segment_id));
create policy track_point_insert_self on track_point for insert with check (
  exists (select 1 from track_segment ts where ts.id = segment_id and ts.operator_id = app_operator_id())
);

-- weighing: manager + owning operator ONLY. Unlike tracks, the spec is
-- explicit that client/city must never see a raw weighing row — they get
-- aggregates exclusively through get_mission_totals() above.
create policy weighing_select on weighing for select using (
  app_role() = 'manager' or operator_id = app_operator_id()
);
create policy weighing_insert_self on weighing for insert with check (operator_id = app_operator_id());
create policy weighing_update_self on weighing for update
  using (operator_id = app_operator_id())
  with check (operator_id = app_operator_id());

-- ============================================================================
-- GRANTS
-- ============================================================================

grant usage on schema public to authenticated;
grant select, insert, update, delete on
  city, client, operator, mission, mission_assignment, track_segment, track_point, weighing, app_user
  to authenticated;
grant execute on function public.get_mission_totals(date, date) to authenticated;
